name: Rust (Linux)

on:
  push:
    branches: [ "version_0_2_0" ]
  pull_request:
    branches: [ "version_0_2_0" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: >-
          sudo apt update && sudo apt install
          libudev-dev
          alsa-base
          libasound2-dev
          ${{ matrix.ui.packages }}
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
